# Generated by CodePress bootstrap-app-server.
# Edits are preserved, but running /codepress-bootstrap-app-server again may overwrite them.
# syntax=docker/dockerfile:1.7
FROM node:22-bookworm

WORKDIR /app

COPY package.json package-lock.json ./
ARG NPM_TOKEN
RUN --mount=type=secret,id=npmrc,target=/run/secrets/npmrc,required=false \
    set -eu; \
    if [ -s /run/secrets/npmrc ]; then cp /run/secrets/npmrc /root/.npmrc; \
    elif [ -n "${NPM_TOKEN:-}" ]; then printf '%s\n' "//registry.tiptap.dev/:_authToken=${NPM_TOKEN}" > /root/.npmrc; \
    fi; \
    npm ci --ignore-scripts; \
    rm -f /root/.npmrc

COPY app ./app
COPY components ./components
COPY config ./config
COPY constants ./constants
COPY contexts ./contexts
COPY hooks ./hooks
COPY lib ./lib
COPY public ./public
COPY services ./services
COPY store ./store
COPY types ./types
COPY utils ./utils
COPY eslint-rules ./eslint-rules
COPY next.config.js middleware.ts tsconfig.json tailwind.config.ts postcss.config.mjs eslint.config.mjs ./

RUN chown -R node:node /app
USER node

EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0"]
