# Generated by CodePress bootstrap-app-server.
# Edits are preserved, but running /codepress-bootstrap-app-server again may overwrite them.
FROM node:22-bookworm

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0"]
