# Generated by CodePress bootstrap-app-server.
# Edits are preserved, but running /codepress-bootstrap-app-server again may overwrite them.
# syntax=docker/dockerfile:1.7
FROM node:22-bookworm

WORKDIR /app

COPY package.json package-lock.json ./
ARG NPM_TOKEN
RUN --mount=type=secret,id=npmrc,target=/run/secrets/npmrc,required=false \
    set -eu; \
    if [ -s /run/secrets/npmrc ]; then cp /run/secrets/npmrc /root/.npmrc; \
    elif [ -n "${NPM_TOKEN:-}" ]; then printf '%s\n' "//registry.tiptap.dev/:_authToken=${NPM_TOKEN}" > /root/.npmrc; \
    fi; \
    npm ci; \
    rm -f /root/.npmrc

COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0"]
