'use client';

import { useEffect, useState } from 'react';
import { generateHTML, type Editor, type JSONContent } from '@tiptap/core';
import sanitizeHtml from 'sanitize-html';
import { ASSISTANT_HTML_SANITIZE_OPTIONS } from '@/components/AgentChat/MarkdownMessage';

/** A presentation-only snapshot: never apply partial blocks to the live editor. */
export function DraftBlockPreview({
  blocks,
  editor,
  fallbackText,
}: {
  readonly blocks: JSONContent[] | null;
  readonly editor: Editor | null;
  readonly fallbackText: string;
}) {
  const [html, setHtml] = useState<string | null>(null);

  useEffect(() => {
    if (!editor || editor.isDestroyed || blocks == null) return;
    try {
      const rendered = generateHTML(
        { type: 'doc', content: blocks },
        editor.extensionManager.extensions
      );
      setHtml(sanitizeHtml(rendered, ASSISTANT_HTML_SANITIZE_OPTIONS));
    } catch {
      // A node type, mark, or text value may still be incomplete. Keep the
      // last renderable snapshot until the next fragment supplies it.
    }
  }, [blocks, editor]);

  if (html == null) {
    return (
      <div className="whitespace-pre-wrap text-base leading-[1.8] text-gray-800">
        {fallbackText}
      </div>
    );
  }

  return (
    <div
      className="text-base leading-[1.8] text-gray-800 break-words [&_p]:my-4 [&_h1]:text-2xl [&_h1]:font-semibold [&_h1]:mb-6 [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:mt-8 [&_h2]:mb-3 [&_h3]:font-semibold [&_h3]:mt-6 [&_h3]:mb-2 [&_ul]:my-4 [&_ul]:list-disc [&_ul]:pl-5 [&_ol]:my-4 [&_ol]:list-decimal [&_ol]:pl-5 [&_li]:my-2 [&_blockquote]:border-l-2 [&_blockquote]:pl-4 [&_a]:text-primary-600 [&_a]:underline [&_pre]:overflow-x-auto [&_pre]:whitespace-pre [&_table]:block [&_table]:overflow-x-auto [&_td]:border [&_td]:p-2 [&_th]:border [&_th]:p-2"
      // Generated by Tiptap and sanitized with the same policy as assistant messages.
      // eslint-disable-next-line react/no-danger
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}
