export const mockInterests = {
  journals: [
    {
      id: 'nature',
      name: 'Nature',
      type: 'journal',
      imageUrl: 'https://media.springernature.com/full/nature-cms/uploads/product/nature/header-86f1267ea01eccd46b530284be10585e.svg',
      description: 'International journal of science',
      followers: 1200000,
      verified: true,
    },
    {
      id: 'science',
      name: 'Science',
      type: 'journal',
      imageUrl: 'https://www.science.org/pb-assets/images/logos/science-logo-share-1200x630-1588263136833.jpg',
      description: 'The world\'s leading outlet for scientific news',
      followers: 980000,
      verified: true,
    },
    {
      id: 'cell',
      name: 'Cell',
      type: 'journal',
      imageUrl: 'https://els-website-assets.s3.amazonaws.com/journal-logo/cell.png',
      description: 'Leading journal in life sciences',
      followers: 750000,
      verified: true,
    },
    {
      id: 'nejm',
      name: 'New England Journal of Medicine',
      type: 'journal',
      imageUrl: 'https://cdn.nejm.org/img/nejm-logo-social.png',
      description: 'Leading medical journal',
      followers: 890000,
      verified: true,
    },
    {
      id: 'lancet',
      name: 'The Lancet',
      type: 'journal',
      imageUrl: 'https://www.thelancet.com/pb-assets/Lancet/marketing/social/social-share-default-1200x630-1585151364685.jpg',
      description: 'One of the world\'s oldest medical journals',
      followers: 820000,
      verified: true,
    },
    {
      id: 'pnas',
      name: 'PNAS',
      type: 'journal',
      imageUrl: 'https://www.pnas.org/pb-assets/images/logo-1645552374437.svg',
      description: 'Proceedings of the National Academy of Sciences',
      followers: 680000,
      verified: true,
    },
    {
      id: 'nature_medicine',
      name: 'Nature Medicine',
      type: 'journal',
      imageUrl: 'https://media.springernature.com/full/nature-cms/uploads/product/nmed/header-8755aaa85bee13a8c3a83a3c5c1294f8.svg',
      description: 'Premier journal for medical research',
      followers: 560000,
      verified: true,
    },
    {
      id: 'nature_biotech',
      name: 'Nature Biotechnology',
      type: 'journal',
      imageUrl: 'https://media.springernature.com/full/nature-cms/uploads/product/nbt/header-8755aaa85bee13a8c3a83a3c5c1294f8.svg',
      description: 'Leading journal in biotechnology',
      followers: 480000,
      verified: true,
    },
    {
      id: 'cell_stem_cell',
      name: 'Cell Stem Cell',
      type: 'journal',
      imageUrl: 'https://els-website-assets.s3.amazonaws.com/journal-logo/cell-stem-cell.png',
      description: 'Research in stem cell biology',
      followers: 320000,
      verified: true,
    },
    {
      id: 'nature_neuro',
      name: 'Nature Neuroscience',
      type: 'journal',
      imageUrl: 'https://media.springernature.com/full/nature-cms/uploads/product/nn/header-8755aaa85bee13a8c3a83a3c5c1294f8.svg',
      description: 'Leading neuroscience research',
      followers: 440000,
      verified: true,
    },
    {
      id: 'immunity',
      name: 'Immunity',
      type: 'journal',
      imageUrl: 'https://els-website-assets.s3.amazonaws.com/journal-logo/immunity.png',
      description: 'Research in immunology',
      followers: 290000,
      verified: true,
    },
    {
      id: 'nature_genetics',
      name: 'Nature Genetics',
      type: 'journal',
      imageUrl: 'https://media.springernature.com/full/nature-cms/uploads/product/ng/header-8755aaa85bee13a8c3a83a3c5c1294f8.svg',
      description: 'Genetics research and methodology',
      followers: 380000,
      verified: true,
    },
    {
      id: 'cell_metabolism',
      name: 'Cell Metabolism',
      type: 'journal',
      imageUrl: 'https://els-website-assets.s3.amazonaws.com/journal-logo/cell-metabolism.png',
      description: 'Cellular metabolism research',
      followers: 270000,
      verified: true,
    },
    {
      id: 'nature_methods',
      name: 'Nature Methods',
      type: 'journal',
      imageUrl: 'https://media.springernature.com/full/nature-cms/uploads/product/nmeth/header-8755aaa85bee13a8c3a83a3c5c1294f8.svg',
      description: 'Scientific methodology and techniques',
      followers: 420000,
      verified: true,
    },
    {
      id: 'molecular_cell',
      name: 'Molecular Cell',
      type: 'journal',
      imageUrl: 'https://els-website-assets.s3.amazonaws.com/journal-logo/molecular-cell.png',
      description: 'Research in molecular biology',
      followers: 310000,
      verified: true,
    },
    {
      id: 'nature_immunology',
      name: 'Nature Immunology',
      type: 'journal',
      imageUrl: 'https://media.springernature.com/full/nature-cms/uploads/product/ni/header-8755aaa85bee13a8c3a83a3c5c1294f8.svg',
      description: 'Immunology research',
      followers: 340000,
      verified: true,
    },
    {
      id: 'developmental_cell',
      name: 'Developmental Cell',
      type: 'journal',
      imageUrl: 'https://els-website-assets.s3.amazonaws.com/journal-logo/developmental-cell.png',
      description: 'Developmental biology research',
      followers: 240000,
      verified: true,
    },
    {
      id: 'genome_research',
      name: 'Genome Research',
      type: 'journal',
      imageUrl: 'https://genome.cshlp.org/site/misc/genome_research_logo.png',
      description: 'Genomics and related research',
      followers: 280000,
      verified: true,
    },
    {
      id: 'nature_chemistry',
      name: 'Nature Chemistry',
      type: 'journal',
      imageUrl: 'https://media.springernature.com/full/nature-cms/uploads/product/nchem/header-8755aaa85bee13a8c3a83a3c5c1294f8.svg',
      description: 'Chemistry research and methodology',
      followers: 300000,
      verified: true,
    },
    {
      id: 'cell_reports',
      name: 'Cell Reports',
      type: 'journal',
      imageUrl: 'https://els-website-assets.s3.amazonaws.com/journal-logo/cell-reports.png',
      description: 'Open access life sciences journal',
      followers: 260000,
      verified: true,
    }
  ],
  people: [
    {
      id: 'jennifer_doudna',
      name: 'Dr. Jennifer Doudna',
      type: 'person',
      imageUrl: 'https://i.pravatar.cc/150?img=1',
      description: 'Nobel laureate, CRISPR pioneer at UC Berkeley',
      followers: 250000,
      verified: true,
    },
    {
      id: 'feng_zhang',
      name: 'Dr. Feng Zhang',
      type: 'person',
      imageUrl: 'https://i.pravatar.cc/150?img=2',
      description: 'CRISPR researcher at MIT-Harvard Broad Institute',
      followers: 180000,
      verified: true,
    },
    {
      id: 'francis_collins',
      name: 'Dr. Francis Collins',
      type: 'person',
      imageUrl: 'https://i.pravatar.cc/150?img=3',
      description: 'Former NIH Director, Human Genome Project leader',
      followers: 220000,
      verified: true,
    },
    {
      id: 'eric_lander',
      name: 'Dr. Eric Lander',
      type: 'person',
      imageUrl: 'https://i.pravatar.cc/150?img=4',
      description: 'Founding director of the Broad Institute',
      followers: 165000,
      verified: true,
    },
    {
      id: 'emmanuelle_charpentier',
      name: 'Dr. Emmanuelle Charpentier',
      type: 'person',
      imageUrl: 'https://i.pravatar.cc/150?img=5',
      description: 'Nobel laureate, CRISPR pioneer',
      followers: 190000,
      verified: true,
    },
    {
      id: 'david_liu',
      name: 'Dr. David Liu',
      type: 'person',
      imageUrl: 'https://i.pravatar.cc/150?img=6',
      description: 'Pioneer in base editing and protein evolution',
      followers: 145000,
      verified: true,
    },
    {
      id: 'mary_claire_king',
      name: 'Dr. Mary-Claire King',
      type: 'person',
      imageUrl: 'https://i.pravatar.cc/150?img=7',
      description: 'Discovered BRCA1 gene, breast cancer research',
      followers: 135000,
      verified: true,
    },
    {
      id: 'george_church',
      name: 'Dr. George Church',
      type: 'person',
      imageUrl: 'https://i.pravatar.cc/150?img=8',
      description: 'Genetics pioneer, synthetic biology researcher',
      followers: 175000,
      verified: true,
    },
    {
      id: 'svante_paabo',
      name: 'Dr. Svante Pääbo',
      type: 'person',
      imageUrl: 'https://i.pravatar.cc/150?img=9',
      description: 'Pioneer in paleogenetics',
      followers: 120000,
      verified: true,
    },
    {
      id: 'yoshinori_ohsumi',
      name: 'Dr. Yoshinori Ohsumi',
      type: 'person',
      imageUrl: 'https://i.pravatar.cc/150?img=10',
      description: 'Nobel laureate, autophagy research',
      followers: 110000,
      verified: true,
    },
    {
      id: 'shinya_yamanaka',
      name: 'Dr. Shinya Yamanaka',
      type: 'person',
      imageUrl: 'https://i.pravatar.cc/150?img=11',
      description: 'Nobel laureate, stem cell research',
      followers: 160000,
      verified: true,
    },
    {
      id: 'carolyn_bertozzi',
      name: 'Dr. Carolyn Bertozzi',
      type: 'person',
      imageUrl: 'https://i.pravatar.cc/150?img=12',
      description: 'Pioneer in bioorthogonal chemistry',
      followers: 140000,
      verified: true,
    },
    {
      id: 'karl_deisseroth',
      name: 'Dr. Karl Deisseroth',
      type: 'person',
      imageUrl: 'https://i.pravatar.cc/150?img=13',
      description: 'Pioneer in optogenetics and CLARITY',
      followers: 130000,
      verified: true,
    },
    {
      id: 'edward_boyden',
      name: 'Dr. Edward Boyden',
      type: 'person',
      imageUrl: 'https://i.pravatar.cc/150?img=14',
      description: 'Pioneer in expansion microscopy',
      followers: 125000,
      verified: true,
    },
    {
      id: 'feng_zhang',
      name: 'Dr. Feng Zhang',
      type: 'person',
      imageUrl: 'https://i.pravatar.cc/150?img=15',
      description: 'CRISPR pioneer, neuroscience researcher',
      followers: 155000,
      verified: true,
    },
    {
      id: 'david_baker',
      name: 'Dr. David Baker',
      type: 'person',
      imageUrl: 'https://i.pravatar.cc/150?img=16',
      description: 'Protein folding and design pioneer',
      followers: 115000,
      verified: true,
    },
    {
      id: 'sharon_peacock',
      name: 'Dr. Sharon Peacock',
      type: 'person',
      imageUrl: 'https://i.pravatar.cc/150?img=17',
      description: 'Leader in pathogen genomics',
      followers: 95000,
      verified: true,
    },
    {
      id: 'sarah_teichmann',
      name: 'Dr. Sarah Teichmann',
      type: 'person',
      imageUrl: 'https://i.pravatar.cc/150?img=18',
      description: 'Pioneer in single-cell genomics',
      followers: 105000,
      verified: true,
    },
    {
      id: 'pardis_sabeti',
      name: 'Dr. Pardis Sabeti',
      type: 'person',
      imageUrl: 'https://i.pravatar.cc/150?img=19',
      description: 'Computational geneticist, disease researcher',
      followers: 100000,
      verified: true,
    },
    {
      id: 'zhang_yongzhen',
      name: 'Dr. Zhang Yongzhen',
      type: 'person',
      imageUrl: 'https://i.pravatar.cc/150?img=20',
      description: 'Virologist, genomics researcher',
      followers: 85000,
      verified: true,
    }
  ],
  topics: [
    {
      id: 'ai',
      name: 'Artificial Intelligence',
      type: 'topic',
      description: 'Machine learning, neural networks, and AI applications',
      followers: 890000,
      verified: true,
    },
    {
      id: 'crispr',
      name: 'CRISPR Technology',
      type: 'topic',
      description: 'Gene editing and therapeutic applications',
      followers: 450000,
      verified: true,
    },
    {
      id: 'quantum_computing',
      name: 'Quantum Computing',
      type: 'topic',
      description: 'Quantum information science and computing',
      followers: 380000,
      verified: true,
    },
    {
      id: 'immunology',
      name: 'Immunology',
      type: 'topic',
      description: 'Immune system and disease research',
      followers: 420000,
      verified: true,
    },
    {
      id: 'neuroscience',
      name: 'Neuroscience',
      type: 'topic',
      description: 'Brain function and nervous system research',
      followers: 520000,
      verified: true,
    },
    {
      id: 'climate_change',
      name: 'Climate Change',
      type: 'topic',
      description: 'Global warming and environmental impact',
      followers: 680000,
      verified: true,
    },
    {
      id: 'renewable_energy',
      name: 'Renewable Energy',
      type: 'topic',
      description: 'Sustainable energy technologies',
      followers: 440000,
      verified: true,
    },
    {
      id: 'cancer_research',
      name: 'Cancer Research',
      type: 'topic',
      description: 'Cancer biology and treatment',
      followers: 560000,
      verified: true,
    },
    {
      id: 'genomics',
      name: 'Genomics',
      type: 'topic',
      description: 'Genome sequencing and analysis',
      followers: 390000,
      verified: true,
    },
    {
      id: 'space_exploration',
      name: 'Space Exploration',
      type: 'topic',
      description: 'Space science and astronomy',
      followers: 720000,
      verified: true,
    },
    {
      id: 'synthetic_biology',
      name: 'Synthetic Biology',
      type: 'topic',
      description: 'Engineering biological systems',
      followers: 280000,
      verified: true,
    },
    {
      id: 'materials_science',
      name: 'Materials Science',
      type: 'topic',
      description: 'Advanced materials and applications',
      followers: 310000,
      verified: true,
    },
    {
      id: 'microbiome',
      name: 'Microbiome',
      type: 'topic',
      description: 'Microbial communities and health',
      followers: 260000,
      verified: true,
    },
    {
      id: 'robotics',
      name: 'Robotics',
      type: 'topic',
      description: 'Robot design and automation',
      followers: 480000,
      verified: true,
    },
    {
      id: 'drug_discovery',
      name: 'Drug Discovery',
      type: 'topic',
      description: 'Pharmaceutical research and development',
      followers: 340000,
      verified: true,
    },
    {
      id: 'biotech',
      name: 'Biotechnology',
      type: 'topic',
      description: 'Biological technology applications',
      followers: 420000,
      verified: true,
    },
    {
      id: 'mental_health',
      name: 'Mental Health',
      type: 'topic',
      description: 'Psychological and psychiatric research',
      followers: 580000,
      verified: true,
    },
    {
      id: 'nanotechnology',
      name: 'Nanotechnology',
      type: 'topic',
      description: 'Nanoscale science and engineering',
      followers: 320000,
      verified: true,
    },
    {
      id: 'bioinformatics',
      name: 'Bioinformatics',
      type: 'topic',
      description: 'Computational biology and data analysis',
      followers: 290000,
      verified: true,
    },
    {
      id: 'regenerative_medicine',
      name: 'Regenerative Medicine',
      type: 'topic',
      description: 'Tissue engineering and stem cells',
      followers: 270000,
      verified: true,
    }
  ]
};

export function fetchInterests(type: 'journal' | 'person' | 'topic') {
  return new Promise((resolve) => {
    setTimeout(() => {
      switch (type) {
        case 'journal':
          resolve(mockInterests.journals);
          break;
        case 'person':
          resolve(mockInterests.people);
          break;
        case 'topic':
          resolve(mockInterests.topics);
          break;
        default:
          resolve([]);
      }
    }, 500);
  });
}

