import { 
  Eye, Quote, MessageSquare, Sparkles, Users, Coins, 
  Tag, Link2, BarChart2, Star
} from 'lucide-react'
import { Paper } from '@/types/paper'

interface PaperRightSidebarProps {
  paper: Paper;
}

export const PaperRightSidebar = ({ paper }: PaperRightSidebarProps) => {
  return (
    <div>
      {/* AI Summary */}
      <div className="mb-8">
        <div className="flex items-center space-x-2 mb-3">
          <h3 className="text-sm font-medium text-gray-900">AI Summary</h3>
          <Sparkles className="h-4 w-4 text-indigo-500" />
        </div>
        <div className="bg-indigo-50 rounded-lg p-4">
          <h4 className="text-sm font-medium text-indigo-900 mb-2">Key Points:</h4>
          <ul className="space-y-2 text-sm text-indigo-900">
            <li className="flex items-start">
              <span className="mr-2">•</span>
              <span>Deoxysphingolipids shown to activate CGAS-STING pathway in colon cancer cells</span>
            </li>
            <li className="flex items-start">
              <span className="mr-2">•</span>
              <span>Enhanced tumor immunity observed through increased T-cell recruitment</span>
            </li>
            <li className="flex items-start">
              <span className="mr-2">•</span>
              <span>Novel therapeutic potential for colon cancer treatment identified</span>
            </li>
          </ul>
          <div className="mt-3 text-xs text-indigo-700">
            Generated by ResearchHub AI
          </div>
        </div>
      </div>

      {/* Paper Metrics */}
      <div className="mb-8">
        <h3 className="text-sm font-medium text-gray-900 mb-4 flex items-center gap-2">
          <BarChart2 className="h-4 w-4 text-gray-500" />
          Paper Metrics
        </h3>
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-1.5 text-gray-500">
              <div className="w-5 h-5 flex items-center justify-center">
                <Eye className="h-4 w-4" />
              </div>
              <span className="text-sm">Views</span>
            </div>
            <span className="text-md font-medium">{paper.metrics.views}</span>
          </div>
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-1.5 text-gray-500">
              <div className="w-5 h-5 flex items-center justify-center">
                <Quote className="h-4 w-4" />
              </div>
              <span className="text-sm">Citations</span>
            </div>
            <span className="text-md font-medium">{paper.metrics.citations}</span>
          </div>
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-1.5 text-gray-500">
              <div className="w-5 h-5 flex items-center justify-center">
                <MessageSquare className="h-4 w-4" />
              </div>
              <span className="text-sm">Comments</span>
            </div>
            <span className="text-md font-medium">{paper.metrics.comments}</span>
          </div>
        </div>
      </div>

      {/* DOI */}
      <div className="mb-8">
        <h3 className="text-sm font-medium text-gray-900 mb-4 flex items-center gap-2">
          <Link2 className="h-4 w-4 text-gray-500" />
          DOI
        </h3>
        <a href={`https://doi.org/${paper.doi}`} 
           className="text-sm text-blue-600 hover:underline"
           target="_blank" 
           rel="noopener noreferrer">
          {paper.doi}
        </a>
      </div>

      {/* RSC Contributors */}
      <div className="mb-8">
        <h3 className="text-sm font-medium text-gray-900 mb-4 flex items-center gap-2">
          <Users className="h-4 w-4 text-gray-500" />
          Top Contributors
        </h3>
        <div className="space-y-3 mb-3">
          {paper.contributors.map((contributor) => (
            <div key={contributor.user.id} className="flex items-center space-x-3">
              {contributor.user.profileImage ? (
                <img 
                  src={contributor.user.profileImage} 
                  alt={contributor.user.fullName}
                  className="h-8 w-8 rounded-full object-cover ring-2 ring-white border border-gray-200" 
                />
              ) : (
                <div className="h-8 w-8 rounded-full bg-gray-200 text-gray-600 flex items-center justify-center text-sm font-medium ring-2 ring-white border border-gray-200">
                  {contributor.user.fullName.split(' ').map(n => n[0]).join('')}
                </div>
              )}
              <div>
                <div className="text-sm font-medium">{contributor.user.fullName}</div>
                <div className="flex items-center space-x-1 text-orange-500">
                  <Coins className="h-3 w-3" />
                  <span className="text-xs">{contributor.amount.toLocaleString()} RSC</span>
                </div>
              </div>
            </div>
          ))}
        </div>
        <button className="text-sm text-indigo-600 hover:text-indigo-700 font-medium">
          See all contributors →
        </button>
      </div>

      {/* Keywords */}
      <div>
        <h3 className="text-sm font-medium text-gray-900 mb-4 flex items-center gap-2">
          <Tag className="h-4 w-4 text-gray-500" />
          Keywords
        </h3>
        <div className="flex flex-wrap gap-2">
          {paper.keywords.map((keyword, i) => (
            <span 
              key={i} 
              className="bg-gray-100 px-2 py-1 rounded-full text-xs text-gray-600"
            >
              {keyword}
            </span>
          ))}
        </div>
      </div>
    </div>
  )
} 