import {
  Microscope,
  FlaskConical,
  Monitor,
  Atom,
  TrendingUp,
  Stethoscope,
  Calculator,
  Wrench,
  Telescope,
  Users,
  Infinity,
  Dna,
  BarChart3,
} from 'lucide-react';

// Category icon mapping
const categoryIcons: Record<string, React.ElementType> = {
  biology: Microscope,
  chemistry: FlaskConical,
  'computer science': Monitor,
  physics: Atom,
  economics: TrendingUp,
  medicine: Stethoscope,
  mathematics: Calculator,
  engineering: Wrench,
  astrophysics: Telescope,
  'social sciences': Users,
  'nonlinear sciences': Infinity,
  biochemistry: Dna,
  statistics: BarChart3,
};

// Category emoji mapping
const categoryEmojis: Record<string, string> = {
  biology: '🧬',
  chemistry: '🧪',
  'computer science': '💻',
  physics: '⚛️',
  economics: '📈',
  medicine: '🏥',
  mathematics: '🔢',
  engineering: '⚙️',
  astrophysics: '🌌',
  'social sciences': '👥',
  'nonlinear sciences': '∞',
  biochemistry: '🧫',
  statistics: '📊',
};

// Subcategory emoji mapping
const subcategoryEmojis: Record<string, string> = {
  // Biology
  paleontology: '🦖',
  pathology: '🔬',
  'evolutionary biology': '🧬',
  neuroscience: '🧠',
  bioinformatics: '💻',
  'systems biology': '🔗',
  genomics: '🧬',
  zoology: '🦁',
  'synthetic biology': '🧪',
  'developmental biology': '🌱',
  ecology: '🌿',
  pharmacology: '💊',
  'cell biology': '🦠',
  biophysics: '⚛️',
  'molecular biology': '🧬',
  physiology: '❤️',
  microbiology: '🦠',
  'cancer biology': '🎗️',
  'plant biology': '🌱',
  'genetics and genomics': '🧬',
  'biological physics': '🔬',
  'quantitative biology': '📊',
  biomolecules: '🧪',
  'molecular networks': '🔗',
  'other quantitative biology': '📈',
  'populations and evolution': '🌍',
  'quantitative methods': '📊',
  'subcellular processes': '🔬',
  'tissues and organs': '🫀',

  // Chemistry
  biochemistry: '🧪',
  'organic chemistry': '🧪',
  'computational chemistry': '💻',
  'physical chemistry': '⚛️',
  'materials science': '🔧',
  'chemical physics': '⚛️',
  'environmental chemistry': '🌿',
  'chemical engineering': '⚙️',
  'nuclear chemistry': '☢️',
  'chemical biology': '🧬',
  'supramolecular chemistry': '🔗',
  catalysis: '⚡',
  'inorganic chemistry': '🧪',
  electrochemistry: '🔋',
  'materials chemistry': '🧱',
  astrochemistry: '🌌',
  'chemical education': '📚',
  'food chemistry': '🍽️',
  geochemistry: '🌍',
  'medicinal chemistry': '💊',
  nanochemistry: '🔬',
  'organometallic chemistry': '⚛️',
  'surface chemistry': '🧲',
  'analytical chemistry': '🔍',

  // Computer Science
  'machine learning': '🤖',
  'software engineering': '💻',
  'computer vision': '👁️',
  graphics: '🎨',
  'information retrieval': '🔍',
  'human–computer interaction': '👤',
  'distributed computing': '🌐',
  'natural language processing': '🗣️',
  'game theory': '🎮',
  'discrete mathematics': '🔢',
  multimedia: '📹',
  'artificial intelligence': '🤖',
  'computational complexity': '🧩',
  'computational geometry': '📐',
  'cryptography and security': '🔐',
  'data structures and algorithms': '🔤',
  databases: '🗄️',
  'formal languages': '📝',
  'hardware architecture': '🖥️',
  'neural computing': '🧠',
  networking: '🌐',
  'operating systems': '⚙️',
  'programming languages': '💻',
  sound: '🎵',
  'quantum computing': '⚛️',
  'computational engineering': '⚙️',
  'computers and society': '👥',
  'digital libraries': '📚',
  'emerging technologies': '🚀',
  'general literature': '📖',
  'multiagent systems': '🤝',
  'mathematical software': '🔢',
  other: '📦',
  performance: '⚡',
  'symbolic computation': '🔣',
  'social networks': '🌐',

  // Physics
  'atomic physics': '⚛️',
  optics: '🔦',
  'computational physics': '💻',
  'statistical mechanics': '📊',
  'fluid dynamics': '💧',
  superconductivity: '🧲',
  'soft matter': '🫧',
  'general relativity': '🌌',
  geophysics: '🌍',
  'mathematical physics': '📐',
  instrumentation: '🔧',
  cosmology: '🌌',
  'condensed matter': '❄️',
  'high energy experiment': '⚡',
  'high energy phenomenology': '🌟',
  'high energy theory': '💫',
  'lattice physics': '🔷',
  'nuclear experiment': '☢️',
  'nuclear theory': '⚛️',
  'plasma physics': '🔥',
  'quantum physics': '⚛️',
  'disordered systems': '🌀',
  'mesoscale physics': '🔬',
  'other condensed matter': '❄️',
  'quantum gases': '💨',
  'strongly correlated': '🔗',
  'general physics': '🔭',
  'accelerator physics': '🚀',
  'atmospheric physics': '🌤️',
  'applied physics': '⚙️',
  'atomic clusters': '⚛️',
  'classical physics': '🎱',
  'physics education': '📚',
  'history of physics': '📜',
  'popular physics': '🌟',
  'space physics': '🚀',
  'data analysis': '📊',

  // Economics
  econometrics: '📊',
  'financial economics': '💰',
  'computational finance': '💻',
  'economic theory': '📈',
  'general economics': '💼',
  'general finance': '💵',
  'mathematical finance': '📐',
  'portfolio management': '📊',
  'quantitative finance': '📈',
  'risk management': '⚠️',
  'securities pricing': '💹',
  'statistical finance': '📊',
  'trading and market microstructure': '📈',

  // Medicine
  'internal medicine': '🏥',
  endocrinology: '💉',
  pediatrics: '👶',
  psychiatry: '🧠',
  radiology: '📷',
  'medical physics': '⚛️',
  'public health': '🏥',
  'physical therapy': '🏃',
  nursing: '👩‍⚕️',
  cardiology: '❤️',
  dentistry: '🦷',
  'medical education': '📚',
  ophthalmology: '👁️',
  'health informatics': '💻',
  gastroenterology: '🔬',
  dermatology: '🧴',
  urology: '🏥',
  'obstetrics and gynecology': '👶',
  neurology: '🧠',
  nephrology: '🏥',
  hematology: '🩸',
  'pain medicine': '💊',
  oncology: '🎗️',
  'emergency medicine': '🚑',
  immunology: '🛡️',
  rheumatology: '🦴',
  'clinical trials': '🧪',
  'critical care medicine': '🚨',
  'health economics': '💰',
  'health policy': '📋',
  'medical ethics': '⚖️',
  nutrition: '🥗',
  'reproductive health': '👶',
  'sports medicine': '🏃',
  epidemiology: '📊',
  anesthesiology: '💉',
  'infectious disease': '🦠',
  orthopedics: '🦴',
  otolaryngology: '👂',
  'palliative medicine': '🤲',
  pulmonology: '🫁',
  surgery: '🏥',

  // Mathematics
  combinatorics: '🔢',
  'information theory': '📡',
  'numerical analysis': '🔢',
  'algebraic geometry': '📐',
  'algebraic topology': '🔷',
  'analysis of pdes': '∂',
  'category theory': '🔗',
  'classical analysis': '📊',
  'commutative algebra': '🔢',
  'complex variables': '🌀',
  'differential geometry': '📐',
  'dynamical systems': '🔄',
  'functional analysis': '📈',
  'general mathematics': '🔢',
  'general topology': '🔷',
  'geometric topology': '📐',
  'group theory': '🔗',
  'history and overview': '📚',
  'k-theory': '🎯',
  logic: '🧩',
  'metric geometry': '📏',
  'number theory': '🔢',
  'operator algebras': '🔤',
  'optimization and control': '🎯',
  probability: '🎲',
  'quantum algebra': '⚛️',
  'representation theory': '🔷',
  'rings and algebras': '⭕',
  'spectral theory': '🌈',
  'symplectic geometry': '🔄',

  // Engineering
  robotics: '🤖',
  'signal processing': '📡',
  bioengineering: '🧬',
  'audio and speech processing': '🎤',
  'image and video processing': '📷',
  'systems and control': '⚙️',

  // Astrophysics
  'planetary science': '🪐',
  galaxies: '🌌',
  'high energy astrophysics': '💫',
  'solar and stellar': '☀️',

  // Social Sciences
  'physics and society': '👥',
  'scientific communication and education': '📚',

  // Nonlinear Sciences
  'adaptation and self organization': '🔄',
  'chaotic dynamics': '🌀',
  'cellular automata': '🔲',
  'pattern formation': '🔷',
  'exactly solvable systems': '✓',

  // Statistics
  applications: '📊',
  methodology: '📈',
  'statistics theory': '📐',
  'general statistics': '📊',
  computation: '💻',
  miscellaneous: '📦',

  // Biochemistry (as a category)
  'analytical biochemistry': '🔬',
};

// Helper functions
export const getCategoryIcon = (category: string) => {
  const normalizedCategory = category.toLowerCase();
  const Icon = categoryIcons[normalizedCategory];
  return Icon || FlaskConical; // Default icon if category not found
};

export const getCategoryEmoji = (category: string): string => {
  const normalizedCategory = category.toLowerCase();
  return categoryEmojis[normalizedCategory] || '📁'; // Default emoji if not found
};

export const getSubcategoryEmoji = (name: string): string => {
  const normalizedName = name.toLowerCase();
  return subcategoryEmojis[normalizedName] || '#'; // Default hashtag for unmapped topics
};
