import { Eye, Quote, MessageSquare, Sparkles } from 'lucide-react'

export const PaperRightSidebar = ({ paper }) => {
  return (
    <div className="w-80 fixed right-0 top-0 bottom-0 border-l bg-white/50 backdrop-blur-sm p-6 overflow-y-auto">
      {/* AI Summary */}
      <div className="mb-8">
        <div className="flex items-center space-x-2 mb-3">
          <h3 className="text-sm font-medium text-gray-900">AI Summary</h3>
          <Sparkles className="h-4 w-4 text-indigo-500" />
        </div>
        <div className="bg-indigo-50 rounded-lg p-4">
          <h4 className="text-sm font-medium text-indigo-900 mb-2">Key Points:</h4>
          <ul className="space-y-2 text-sm text-indigo-900">
            <li className="flex items-start">
              <span className="mr-2">•</span>
              <span>Deoxysphingolipids shown to activate CGAS-STING pathway in colon cancer cells</span>
            </li>
            <li className="flex items-start">
              <span className="mr-2">•</span>
              <span>Enhanced tumor immunity observed through increased T-cell recruitment</span>
            </li>
            <li className="flex items-start">
              <span className="mr-2">•</span>
              <span>Novel therapeutic potential for colon cancer treatment identified</span>
            </li>
          </ul>
          <div className="mt-3 text-xs text-indigo-700">
            Generated by ResearchHub AI
          </div>
        </div>
      </div>

      {/* Paper Metrics */}
      <div className="mb-8">
        <h3 className="text-sm font-medium text-gray-900 mb-3">Paper Metrics</h3>
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-1.5 text-gray-500">
              <div className="w-5 h-5 flex items-center justify-center">
                <Eye className="h-4 w-4" />
              </div>
              <span className="text-sm">Views</span>
            </div>
            <span className="text-md font-medium">{paper.metrics.views}</span>
          </div>
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-1.5 text-gray-500">
              <div className="w-5 h-5 flex items-center justify-center">
                <Quote className="h-4 w-4" />
              </div>
              <span className="text-sm">Citations</span>
            </div>
            <span className="text-md font-medium">{paper.metrics.citations}</span>
          </div>
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-1.5 text-gray-500">
              <div className="w-5 h-5 flex items-center justify-center">
                <MessageSquare className="h-4 w-4 scale-[1.3]" />
              </div>
              <span className="text-sm">Comments</span>
            </div>
            <span className="text-md font-medium">{paper.metrics.comments}</span>
          </div>
        </div>
      </div>

      {/* RSC Contributors */}
      <div>
        <h3 className="text-sm font-medium text-gray-900 mb-3">Top Contributors</h3>
        <div className="space-y-3 mb-3">
          <div className="flex items-center space-x-3">
            <div className="h-8 w-8 rounded-full bg-pink-100 text-pink-600 flex items-center justify-center text-sm font-medium">
              AC
            </div>
            <div>
              <div className="text-sm font-medium">Alice Chen</div>
              <div className="text-xs text-gray-500">1,250 RSC</div>
            </div>
          </div>
          <div className="flex items-center space-x-3">
            <div className="h-8 w-8 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center text-sm font-medium">
              BS
            </div>
            <div>
              <div className="text-sm font-medium">Bob Smith</div>
              <div className="text-xs text-gray-500">850 RSC</div>
            </div>
          </div>
          <div className="flex items-center space-x-3">
            <div className="h-8 w-8 rounded-full bg-purple-100 text-purple-600 flex items-center justify-center text-sm font-medium">
              CJ
            </div>
            <div>
              <div className="text-sm font-medium">Carol Johnson</div>
              <div className="text-xs text-gray-500">725 RSC</div>
            </div>
          </div>
          <div className="flex items-center space-x-3">
            <div className="h-8 w-8 rounded-full bg-green-100 text-green-600 flex items-center justify-center text-sm font-medium">
              DW
            </div>
            <div>
              <div className="text-sm font-medium">David Wilson</div>
              <div className="text-xs text-gray-500">500 RSC</div>
            </div>
          </div>
          <div className="flex items-center space-x-3">
            <div className="h-8 w-8 rounded-full bg-orange-100 text-orange-600 flex items-center justify-center text-sm font-medium">
              EB
            </div>
            <div>
              <div className="text-sm font-medium">Emma Brown</div>
              <div className="text-xs text-gray-500">450 RSC</div>
            </div>
          </div>
        </div>
        <button className="text-sm text-indigo-600 hover:text-indigo-700 font-medium">
          See all contributors →
        </button>
      </div>
    </div>
  )
} 